#! /bin/sh

pkill picom
pkill polybar

#Hide bar in FullScreen Window
wm-restack = bspwm

#Apps Initializing
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
pulseaudio&

#Config telai
$HOME/Documentos/screenreal.sh     


#Lauch polybar
$HOME/.config/polybar/launch.sh --forest

#Wallpaper
feh --bg-scale /usr/share/backgrounds/wallpaper-supimpa.jpg


bspc config border_width         1
bspc config window_gap          10


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#focus in the mouse
bspc config focus_follows_pointer true
bspc monitor -d          

#Monitor Color
bspc config normal_border_color "#3341CF"
#bspc config active_border_color "#010011"
bspc config focused_border_color "#6b00f9"
bspc config presel_feedback_color "#3341CF"


#rule to workspace
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=offi
bspc rule -a URxvt desktop='^1' state=tiled follow=on
